version: "3"

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:rw
    networks:
      - project_public_network

  openproject:
    image: openproject/community:12
    container_name: openprojectapp
    environment:
      OPENPROJECT_HOST__NAME: "openproject.platform.jalantechnologies.com"
      OPENPROJECT_SECRET_KEY_BASE: "secret"
    volumes:
      - openproject_data:/var/openproject/pgdata
      - openproject_assets:/var/openproject/assets
    ports:
      - "8080:80"
    networks:
      - project_public_network

volumes:
  openproject_data:
  openproject_assets:

networks:
  project_public_network:
    external: true
